/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espacediet (void)
{
  GtkWidget *espacediet;
  GtkWidget *fixed3;
  GtkWidget *notebookmain_diet;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *fixed10;
  GtkWidget *bienv_diet;
  GtkWidget *label1;
  GtkWidget *fixed11;
  GtkWidget *profil_diet_book;
  GtkWidget *fixed13;
  GtkWidget *pentry_diet1;
  GtkWidget *pentry_diet3;
  GtkWidget *pentry_diet2;
  GtkWidget *pentry_diet4;
  GtkObject *pspin_diet2_adj;
  GtkWidget *pspin_diet2;
  GtkObject *pspin_diet3_adj;
  GtkWidget *pspin_diet3;
  GtkObject *pspin_diet1_adj;
  GtkWidget *pspin_diet1;
  GtkWidget *plabel_diet2;
  GtkWidget *plabel_diet3;
  GtkWidget *plabel_diet5;
  GtkWidget *plabel_diet6;
  GtkWidget *pcombo_diet1;
  GtkWidget *pmodifier_diet1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label28;
  GtkWidget *plabel_diet4;
  GtkWidget *plabel_diet1;
  GtkWidget *imagenom_diet;
  GtkWidget *imageprenom_diet;
  GtkWidget *imagecin_diet;
  GtkWidget *imagetel_diet;
  GtkWidget *label6;
  GtkWidget *fixed14;
  GtkWidget *pentry_diet;
  GtkWidget *pentry_diet6;
  GtkWidget *pentry_diet7;
  GtkWidget *plabel_diet9;
  GtkWidget *plabel_diet8;
  GtkWidget *plabel_diet7;
  GtkWidget *validerp_diet;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *toolbar6;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *modifierprofil_diet;
  GtkWidget *changepass_diet;
  GtkWidget *label2;
  GtkWidget *fixed16;
  GtkWidget *entryfiche_diet1;
  GtkWidget *entryfiche_diet2;
  GtkWidget *entryfiche_diet3;
  GtkWidget *entryfiche_diet4;
  GtkWidget *entryfiche_diet5;
  GtkWidget *toolbar7;
  GtkWidget *afficher1_diet;
  GtkWidget *afficher2_diet;
  GtkWidget *toolbar8;
  GtkWidget *ajouterfiche_diet;
  GtkWidget *suprimerfiche_diet;
  GtkWidget *modifierfiche_diet;
  GtkWidget *entryfiche_diet6;
  GtkWidget *entryfiche_diet8;
  GtkWidget *entryfiche_diet7;
  GtkWidget *prenomfiche_diet;
  GtkWidget *nomfiche_diet;
  GtkWidget *cinfiche_diet;
  GtkWidget *poidfiche_diet;
  GtkWidget *taillefiche_diet;
  GtkWidget *label33;
  GtkWidget *tailltourfiche_diet;
  GtkWidget *regimefiche_diet;
  GtkWidget *affichagebook_diet;
  GtkWidget *fixed17;
  GtkWidget *image3;
  GtkWidget *image4;
  GtkWidget *Guide_diet;
  GtkWidget *guide2_diet;
  GtkWidget *label31;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1_diet;
  GtkWidget *label29;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview2_diet;
  GtkWidget *label30;
  GtkWidget *label3;
  GtkWidget *fixed15;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview3_diet;
  GtkWidget *label32;
  GtkWidget *entry1_diet;
  GtkWidget *entry2_diet;
  GtkWidget *entry3_diet;
  GtkWidget *entry4_diet;
  GtkWidget *entry5_diet;
  GtkWidget *consulter_diet1;
  GtkWidget *consulter_diet2;
  GtkWidget *consulter_diet5;
  GtkWidget *consulter_diet3;
  GtkWidget *consulter_diet4;
  GtkWidget *label4;
  GtkWidget *empty_notebook_page;
  GtkWidget *label5;
  GtkWidget *toolbar5;
  GtkWidget *acc_diet;
  GtkWidget *profil_diet5;
  GtkWidget *dichediet;
  GtkWidget *fichemed_diet;
  GtkWidget *rend_diet;
  GtkWidget *dec_diet;
  GtkWidget *quit_diet;

  espacediet = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (espacediet, 780, 550);
  gtk_window_set_title (GTK_WINDOW (espacediet), _("Espace di\303\251t\303\251ticien"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (espacediet), fixed3);

  notebookmain_diet = gtk_notebook_new ();
  gtk_widget_show (notebookmain_diet);
  gtk_fixed_put (GTK_FIXED (fixed3), notebookmain_diet, 0, 72);
  gtk_widget_set_size_request (notebookmain_diet, 780, 479);
  GTK_WIDGET_UNSET_FLAGS (notebookmain_diet, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (notebookmain_diet), FALSE);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebookmain_diet), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebookmain_diet), vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_box_pack_start (GTK_BOX (vbox2), fixed10, TRUE, TRUE, 0);

  bienv_diet = gtk_label_new (_("<span  size=\"24000\" style=\"italic\">Bienvenue \303\240 l'espace di\303\251t\303\251tique !</span>"));
  gtk_widget_show (bienv_diet);
  gtk_fixed_put (GTK_FIXED (fixed10), bienv_diet, 192, 184);
  gtk_widget_set_size_request (bienv_diet, 405, 32);
  gtk_label_set_use_markup (GTK_LABEL (bienv_diet), TRUE);

  label1 = gtk_label_new (_("label1"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_diet), 0), label1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebookmain_diet), fixed11);

  profil_diet_book = gtk_notebook_new ();
  gtk_widget_show (profil_diet_book);
  gtk_fixed_put (GTK_FIXED (fixed11), profil_diet_book, 2, 0);
  gtk_widget_set_size_request (profil_diet_book, 577, 349);
  GTK_WIDGET_UNSET_FLAGS (profil_diet_book, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (profil_diet_book), FALSE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (profil_diet_book), fixed13);

  pentry_diet1 = gtk_entry_new ();
  gtk_widget_show (pentry_diet1);
  gtk_fixed_put (GTK_FIXED (fixed13), pentry_diet1, 88, 40);
  gtk_widget_set_size_request (pentry_diet1, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet1), 8226);

  pentry_diet3 = gtk_entry_new ();
  gtk_widget_show (pentry_diet3);
  gtk_fixed_put (GTK_FIXED (fixed13), pentry_diet3, 88, 112);
  gtk_widget_set_size_request (pentry_diet3, 160, 24);
  gtk_editable_set_editable (GTK_EDITABLE (pentry_diet3), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet3), 8226);

  pentry_diet2 = gtk_entry_new ();
  gtk_widget_show (pentry_diet2);
  gtk_fixed_put (GTK_FIXED (fixed13), pentry_diet2, 328, 40);
  gtk_widget_set_size_request (pentry_diet2, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet2), 8226);

  pentry_diet4 = gtk_entry_new ();
  gtk_widget_show (pentry_diet4);
  gtk_fixed_put (GTK_FIXED (fixed13), pentry_diet4, 328, 104);
  gtk_widget_set_size_request (pentry_diet4, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet4), 8226);

  pspin_diet2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  pspin_diet2 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_diet2_adj), 1, 0);
  gtk_widget_show (pspin_diet2);
  gtk_fixed_put (GTK_FIXED (fixed13), pspin_diet2, 256, 168);
  gtk_widget_set_size_request (pspin_diet2, 80, 24);

  pspin_diet3_adj = gtk_adjustment_new (1980, 1950, 2020, 1, 10, 10);
  pspin_diet3 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_diet3_adj), 1, 0);
  gtk_widget_show (pspin_diet3);
  gtk_fixed_put (GTK_FIXED (fixed13), pspin_diet3, 352, 168);
  gtk_widget_set_size_request (pspin_diet3, 104, 24);

  pspin_diet1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  pspin_diet1 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_diet1_adj), 1, 0);
  gtk_widget_show (pspin_diet1);
  gtk_fixed_put (GTK_FIXED (fixed13), pspin_diet1, 144, 168);
  gtk_widget_set_size_request (pspin_diet1, 84, 24);

  plabel_diet2 = gtk_label_new (_("Prenom"));
  gtk_widget_show (plabel_diet2);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet2, 280, 48);
  gtk_widget_set_size_request (plabel_diet2, 45, 16);

  plabel_diet3 = gtk_label_new (_("CIN"));
  gtk_widget_show (plabel_diet3);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet3, 48, 120);
  gtk_widget_set_size_request (plabel_diet3, 44, 16);

  plabel_diet5 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (plabel_diet5);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet5, 48, 176);
  gtk_widget_set_size_request (plabel_diet5, 100, 16);

  plabel_diet6 = gtk_label_new (_("Sexe"));
  gtk_widget_show (plabel_diet6);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet6, 192, 240);
  gtk_widget_set_size_request (plabel_diet6, 44, 16);

  pcombo_diet1 = gtk_combo_box_new_text ();
  gtk_widget_show (pcombo_diet1);
  gtk_fixed_put (GTK_FIXED (fixed13), pcombo_diet1, 240, 232);
  gtk_widget_set_size_request (pcombo_diet1, 120, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pcombo_diet1), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pcombo_diet1), _("Femme"));

  pmodifier_diet1 = gtk_button_new ();
  gtk_widget_show (pmodifier_diet1);
  gtk_fixed_put (GTK_FIXED (fixed13), pmodifier_diet1, 240, 288);
  gtk_widget_set_size_request (pmodifier_diet1, 104, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (pmodifier_diet1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox1), label28, FALSE, FALSE, 0);

  plabel_diet4 = gtk_label_new (_("label11"));
  gtk_widget_show (plabel_diet4);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet4, 280, 112);
  gtk_widget_set_size_request (plabel_diet4, 44, 16);

  plabel_diet1 = gtk_label_new (_("Nom"));
  gtk_widget_show (plabel_diet1);
  gtk_fixed_put (GTK_FIXED (fixed13), plabel_diet1, 48, 48);
  gtk_widget_set_size_request (plabel_diet1, 37, 16);

  imagenom_diet = create_pixmap (espacediet, NULL);
  gtk_widget_show (imagenom_diet);
  gtk_fixed_put (GTK_FIXED (fixed13), imagenom_diet, 248, 40);
  gtk_widget_set_size_request (imagenom_diet, 21, 21);

  imageprenom_diet = create_pixmap (espacediet, NULL);
  gtk_widget_show (imageprenom_diet);
  gtk_fixed_put (GTK_FIXED (fixed13), imageprenom_diet, 464, 40);
  gtk_widget_set_size_request (imageprenom_diet, 21, 21);

  imagecin_diet = create_pixmap (espacediet, NULL);
  gtk_widget_show (imagecin_diet);
  gtk_fixed_put (GTK_FIXED (fixed13), imagecin_diet, 248, 112);
  gtk_widget_set_size_request (imagecin_diet, 21, 21);

  imagetel_diet = create_pixmap (espacediet, NULL);
  gtk_widget_show (imagetel_diet);
  gtk_fixed_put (GTK_FIXED (fixed13), imagetel_diet, 464, 104);
  gtk_widget_set_size_request (imagetel_diet, 21, 21);

  label6 = gtk_label_new (_("label6"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (profil_diet_book), gtk_notebook_get_nth_page (GTK_NOTEBOOK (profil_diet_book), 0), label6);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (profil_diet_book), fixed14);

  pentry_diet = gtk_entry_new ();
  gtk_widget_show (pentry_diet);
  gtk_fixed_put (GTK_FIXED (fixed14), pentry_diet, 240, 64);
  gtk_widget_set_size_request (pentry_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet), 8226);

  pentry_diet6 = gtk_entry_new ();
  gtk_widget_show (pentry_diet6);
  gtk_fixed_put (GTK_FIXED (fixed14), pentry_diet6, 240, 120);
  gtk_widget_set_size_request (pentry_diet6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet6), 8226);

  pentry_diet7 = gtk_entry_new ();
  gtk_widget_show (pentry_diet7);
  gtk_fixed_put (GTK_FIXED (fixed14), pentry_diet7, 240, 176);
  gtk_widget_set_size_request (pentry_diet7, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_diet7), 8226);

  plabel_diet9 = gtk_label_new (_("Confirmer mot de passe"));
  gtk_widget_show (plabel_diet9);
  gtk_fixed_put (GTK_FIXED (fixed14), plabel_diet9, 88, 184);
  gtk_widget_set_size_request (plabel_diet9, 148, 16);

  plabel_diet8 = gtk_label_new (_("Nouveau mot de passe"));
  gtk_widget_show (plabel_diet8);
  gtk_fixed_put (GTK_FIXED (fixed14), plabel_diet8, 96, 128);
  gtk_widget_set_size_request (plabel_diet8, 140, 16);

  plabel_diet7 = gtk_label_new (_("Ancien mot de passe"));
  gtk_widget_show (plabel_diet7);
  gtk_fixed_put (GTK_FIXED (fixed14), plabel_diet7, 112, 72);
  gtk_widget_set_size_request (plabel_diet7, 124, 16);

  validerp_diet = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (validerp_diet);
  gtk_fixed_put (GTK_FIXED (fixed14), validerp_diet, 264, 280);
  gtk_widget_set_size_request (validerp_diet, 59, 26);

  image2 = create_pixmap (espacediet, NULL);
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed14), image2, 400, 64);
  gtk_widget_set_size_request (image2, 21, 21);

  label7 = gtk_label_new (_("label7"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (profil_diet_book), gtk_notebook_get_nth_page (GTK_NOTEBOOK (profil_diet_book), 1), label7);

  toolbar6 = gtk_toolbar_new ();
  gtk_widget_show (toolbar6);
  gtk_fixed_put (GTK_FIXED (fixed11), toolbar6, 501, 76);
  gtk_widget_set_size_request (toolbar6, 66, 160);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar6), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_orientation (GTK_TOOLBAR (toolbar6), GTK_ORIENTATION_VERTICAL);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar6));

  tmp_image = gtk_image_new_from_stock ("gtk-orientation-landscape", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  modifierprofil_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Modifier \n   profil"));
  gtk_widget_show (modifierprofil_diet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (modifierprofil_diet), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (modifierprofil_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar6), modifierprofil_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-paste", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  changepass_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Mot de \n  passe"));
  gtk_widget_show (changepass_diet);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (changepass_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar6), changepass_diet);

  label2 = gtk_label_new (_("label2"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_diet), 1), label2);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebookmain_diet), fixed16);

  entryfiche_diet1 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet1);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet1, 480, 96);
  gtk_widget_set_size_request (entryfiche_diet1, 112, 24);
  gtk_editable_set_editable (GTK_EDITABLE (entryfiche_diet1), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet1), 8226);

  entryfiche_diet2 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet2);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet2, 640, 96);
  gtk_widget_set_size_request (entryfiche_diet2, 112, 24);
  gtk_editable_set_editable (GTK_EDITABLE (entryfiche_diet2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet2), 8226);

  entryfiche_diet3 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet3);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet3, 480, 152);
  gtk_widget_set_size_request (entryfiche_diet3, 272, 24);
  gtk_editable_set_editable (GTK_EDITABLE (entryfiche_diet3), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet3), 8226);

  entryfiche_diet4 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet4);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet4, 480, 208);
  gtk_widget_set_size_request (entryfiche_diet4, 272, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet4), 8226);

  entryfiche_diet5 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet5);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet5, 480, 264);
  gtk_widget_set_size_request (entryfiche_diet5, 272, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet5), 8226);

  toolbar7 = gtk_toolbar_new ();
  gtk_widget_show (toolbar7);
  gtk_fixed_put (GTK_FIXED (fixed16), toolbar7, 143, 8);
  gtk_widget_set_size_request (toolbar7, 153, 67);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar7), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar7));

  tmp_image = gtk_image_new_from_stock ("gtk-fullscreen", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  afficher1_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("  Afficher\nAdh\303\251rents"));
  gtk_widget_show (afficher1_diet);
  gtk_container_add (GTK_CONTAINER (toolbar7), afficher1_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-leave-fullscreen", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  afficher2_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _(" Afficher\nles fiches"));
  gtk_widget_show (afficher2_diet);
  gtk_container_add (GTK_CONTAINER (toolbar7), afficher2_diet);

  toolbar8 = gtk_toolbar_new ();
  gtk_widget_show (toolbar8);
  gtk_fixed_put (GTK_FIXED (fixed16), toolbar8, 522, 13);
  gtk_widget_set_size_request (toolbar8, 185, 56);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar8), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar8));

  tmp_image = gtk_image_new_from_stock ("gtk-new", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  ajouterfiche_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Ajouter"));
  gtk_widget_show (ajouterfiche_diet);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (ajouterfiche_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8), ajouterfiche_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  suprimerfiche_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Suprimer"));
  gtk_widget_show (suprimerfiche_diet);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (suprimerfiche_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8), suprimerfiche_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  modifierfiche_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Modifier"));
  gtk_widget_show (modifierfiche_diet);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (modifierfiche_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8), modifierfiche_diet);

  entryfiche_diet6 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet6);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet6, 480, 320);
  gtk_widget_set_size_request (entryfiche_diet6, 272, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet6), 8226);

  entryfiche_diet8 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet8);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet8, 480, 432);
  gtk_widget_set_size_request (entryfiche_diet8, 272, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet8), 8226);

  entryfiche_diet7 = gtk_entry_new ();
  gtk_widget_show (entryfiche_diet7);
  gtk_fixed_put (GTK_FIXED (fixed16), entryfiche_diet7, 480, 376);
  gtk_widget_set_size_request (entryfiche_diet7, 272, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_diet7), 8226);

  prenomfiche_diet = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenomfiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), prenomfiche_diet, 640, 80);
  gtk_widget_set_size_request (prenomfiche_diet, 56, 16);
  gtk_label_set_line_wrap (GTK_LABEL (prenomfiche_diet), TRUE);

  nomfiche_diet = gtk_label_new (_("Nom"));
  gtk_widget_show (nomfiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), nomfiche_diet, 472, 80);
  gtk_widget_set_size_request (nomfiche_diet, 44, 16);

  cinfiche_diet = gtk_label_new (_("CIN"));
  gtk_widget_show (cinfiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), cinfiche_diet, 480, 136);
  gtk_widget_set_size_request (cinfiche_diet, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (cinfiche_diet), TRUE);

  poidfiche_diet = gtk_label_new (_("Poid"));
  gtk_widget_show (poidfiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), poidfiche_diet, 480, 192);
  gtk_widget_set_size_request (poidfiche_diet, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (poidfiche_diet), TRUE);

  taillefiche_diet = gtk_label_new (_("Taille"));
  gtk_widget_show (taillefiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), taillefiche_diet, 480, 248);
  gtk_widget_set_size_request (taillefiche_diet, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (taillefiche_diet), TRUE);

  label33 = gtk_label_new (_("IMC"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed16), label33, 480, 304);
  gtk_widget_set_size_request (label33, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label33), TRUE);

  tailltourfiche_diet = gtk_label_new (_("Tour de taille"));
  gtk_widget_show (tailltourfiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), tailltourfiche_diet, 480, 360);
  gtk_widget_set_size_request (tailltourfiche_diet, 80, 16);
  gtk_label_set_line_wrap (GTK_LABEL (tailltourfiche_diet), TRUE);

  regimefiche_diet = gtk_label_new (_("Type r\303\251gime"));
  gtk_widget_show (regimefiche_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), regimefiche_diet, 480, 416);
  gtk_widget_set_size_request (regimefiche_diet, 72, 16);
  gtk_label_set_line_wrap (GTK_LABEL (regimefiche_diet), TRUE);

  affichagebook_diet = gtk_notebook_new ();
  gtk_widget_show (affichagebook_diet);
  gtk_fixed_put (GTK_FIXED (fixed16), affichagebook_diet, 16, 78);
  gtk_widget_set_size_request (affichagebook_diet, 438, 387);
  GTK_WIDGET_UNSET_FLAGS (affichagebook_diet, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (affichagebook_diet), FALSE);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (affichagebook_diet), fixed17);

  image3 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed17), image3, 48, 112);
  gtk_widget_set_size_request (image3, 40, 40);

  image4 = gtk_image_new_from_stock ("gtk-leave-fullscreen", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed17), image4, 56, 200);
  gtk_widget_set_size_request (image4, 24, 24);

  Guide_diet = gtk_label_new (_("<span style=\"italic\" >Clickez sur afficher les adh\303\251rents pour afficher les adh\303\251rents qui n'ont pas encore une fiche di\303\251t\303\251tique.</span>"));
  gtk_widget_show (Guide_diet);
  gtk_fixed_put (GTK_FIXED (fixed17), Guide_diet, 88, 96);
  gtk_widget_set_size_request (Guide_diet, 320, 72);
  gtk_label_set_use_markup (GTK_LABEL (Guide_diet), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (Guide_diet), TRUE);

  guide2_diet = gtk_label_new (_("<span style=\"italic\" >Clickez sur afficher les fiches pour afficher toutes les fiches di\303\251t\303\251tique.</span>"));
  gtk_widget_show (guide2_diet);
  gtk_fixed_put (GTK_FIXED (fixed17), guide2_diet, 88, 176);
  gtk_widget_set_size_request (guide2_diet, 320, 72);
  gtk_label_set_use_markup (GTK_LABEL (guide2_diet), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (guide2_diet), TRUE);

  label31 = gtk_label_new (_("label31"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (affichagebook_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (affichagebook_diet), 0), label31);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (affichagebook_diet), scrolledwindow1);

  treeview1_diet = gtk_tree_view_new ();
  gtk_widget_show (treeview1_diet);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1_diet);

  label29 = gtk_label_new (_("label29"));
  gtk_widget_show (label29);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (affichagebook_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (affichagebook_diet), 1), label29);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (affichagebook_diet), scrolledwindow2);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_ETCHED_OUT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (viewport1), scrolledwindow3);

  treeview2_diet = gtk_tree_view_new ();
  gtk_widget_show (treeview2_diet);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview2_diet);

  label30 = gtk_label_new (_("label30"));
  gtk_widget_show (label30);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (affichagebook_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (affichagebook_diet), 2), label30);

  label3 = gtk_label_new (_("label3"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_diet), 2), label3);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebookmain_diet), fixed15);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed15), notebook1, 35, 30);
  gtk_widget_set_size_request (notebook1, 318, 320);
  GTK_WIDGET_UNSET_FLAGS (notebook1, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (notebook1), FALSE);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow4);

  treeview3_diet = gtk_tree_view_new ();
  gtk_widget_show (treeview3_diet);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview3_diet);

  label32 = gtk_label_new (_("label32"));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label32);

  entry1_diet = gtk_entry_new ();
  gtk_widget_show (entry1_diet);
  gtk_fixed_put (GTK_FIXED (fixed15), entry1_diet, 368, 48);
  gtk_widget_set_size_request (entry1_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_diet), 8226);

  entry2_diet = gtk_entry_new ();
  gtk_widget_show (entry2_diet);
  gtk_fixed_put (GTK_FIXED (fixed15), entry2_diet, 368, 112);
  gtk_widget_set_size_request (entry2_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_diet), 8226);

  entry3_diet = gtk_entry_new ();
  gtk_widget_show (entry3_diet);
  gtk_fixed_put (GTK_FIXED (fixed15), entry3_diet, 368, 176);
  gtk_widget_set_size_request (entry3_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_diet), 8226);

  entry4_diet = gtk_entry_new ();
  gtk_widget_show (entry4_diet);
  gtk_fixed_put (GTK_FIXED (fixed15), entry4_diet, 368, 240);
  gtk_widget_set_size_request (entry4_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_diet), 8226);

  entry5_diet = gtk_entry_new ();
  gtk_widget_show (entry5_diet);
  gtk_fixed_put (GTK_FIXED (fixed15), entry5_diet, 368, 312);
  gtk_widget_set_size_request (entry5_diet, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_diet), 8226);

  consulter_diet1 = gtk_label_new (_("Nom"));
  gtk_widget_show (consulter_diet1);
  gtk_fixed_put (GTK_FIXED (fixed15), consulter_diet1, 368, 32);
  gtk_widget_set_size_request (consulter_diet1, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (consulter_diet1), TRUE);

  consulter_diet2 = gtk_label_new (_("Prenom"));
  gtk_widget_show (consulter_diet2);
  gtk_fixed_put (GTK_FIXED (fixed15), consulter_diet2, 368, 96);
  gtk_widget_set_size_request (consulter_diet2, 48, 16);
  gtk_label_set_line_wrap (GTK_LABEL (consulter_diet2), TRUE);

  consulter_diet5 = gtk_label_new (_("label40"));
  gtk_widget_show (consulter_diet5);
  gtk_fixed_put (GTK_FIXED (fixed15), consulter_diet5, 368, 296);
  gtk_widget_set_size_request (consulter_diet5, 44, 16);

  consulter_diet3 = gtk_label_new (_("CIN"));
  gtk_widget_show (consulter_diet3);
  gtk_fixed_put (GTK_FIXED (fixed15), consulter_diet3, 368, 160);
  gtk_widget_set_size_request (consulter_diet3, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (consulter_diet3), TRUE);

  consulter_diet4 = gtk_label_new (_("Age"));
  gtk_widget_show (consulter_diet4);
  gtk_fixed_put (GTK_FIXED (fixed15), consulter_diet4, 368, 224);
  gtk_widget_set_size_request (consulter_diet4, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (consulter_diet4), TRUE);

  label4 = gtk_label_new (_("label4"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_diet), 3), label4);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebookmain_diet), empty_notebook_page);

  label5 = gtk_label_new (_("label5"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_diet), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_diet), 4), label5);

  toolbar5 = gtk_toolbar_new ();
  gtk_widget_show (toolbar5);
  gtk_fixed_put (GTK_FIXED (fixed3), toolbar5, 56, 0);
  gtk_widget_set_size_request (toolbar5, 680, 72);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar5), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar5));

  tmp_image = gtk_image_new_from_stock ("gtk-home", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  acc_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Accueil"));
  gtk_widget_show (acc_diet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (acc_diet), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (acc_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5), acc_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-orientation-portrait", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  profil_diet5 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Profil"));
  gtk_widget_show (profil_diet5);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (profil_diet5), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar5), profil_diet5);

  tmp_image = gtk_image_new_from_stock ("gtk-copy", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  dichediet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Fiches di\303\251t\303\251tique"));
  gtk_widget_show (dichediet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (dichediet), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (dichediet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5), dichediet);

  tmp_image = gtk_image_new_from_stock ("gtk-index", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  fichemed_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Fiches m\303\251dicaux"));
  gtk_widget_show (fichemed_diet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (fichemed_diet), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (fichemed_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5), fichemed_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  rend_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Les Rendez-vous"));
  gtk_widget_show (rend_diet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (rend_diet), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (rend_diet), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5), rend_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-goto-first", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  dec_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("D\303\251connexion"));
  gtk_widget_show (dec_diet);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (dec_diet), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar5), dec_diet);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  quit_diet = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Quitter"));
  gtk_widget_show (quit_diet);
  gtk_container_add (GTK_CONTAINER (toolbar5), quit_diet);

  g_signal_connect ((gpointer) pmodifier_diet1, "clicked",
                    G_CALLBACK (on_pmodifier_diet1_clicked),
                    NULL);
  g_signal_connect ((gpointer) validerp_diet, "clicked",
                    G_CALLBACK (on_validerp_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierprofil_diet, "clicked",
                    G_CALLBACK (on_modifierprofil_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) changepass_diet, "clicked",
                    G_CALLBACK (on_changepass_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher1_diet, "clicked",
                    G_CALLBACK (on_afficher1_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher2_diet, "clicked",
                    G_CALLBACK (on_afficher2_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterfiche_diet, "clicked",
                    G_CALLBACK (on_ajouterfiche_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) suprimerfiche_diet, "clicked",
                    G_CALLBACK (on_suprimerfiche_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierfiche_diet, "clicked",
                    G_CALLBACK (on_modifierfiche_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1_diet, "row_activated",
                    G_CALLBACK (on_treeview1_diet_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview2_diet, "row_activated",
                    G_CALLBACK (on_treeview2_diet_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview3_diet, "row_activated",
                    G_CALLBACK (on_treeview3_diet_row_activated),
                    NULL);
  g_signal_connect ((gpointer) acc_diet, "clicked",
                    G_CALLBACK (on_accuei_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) profil_diet5, "clicked",
                    G_CALLBACK (on_profil_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) dichediet, "clicked",
                    G_CALLBACK (on_fchdiet_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) fichemed_diet, "clicked",
                    G_CALLBACK (on_fichemed_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) rend_diet, "clicked",
                    G_CALLBACK (on_rendez_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) dec_diet, "clicked",
                    G_CALLBACK (on_dec_diet_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit_diet, "clicked",
                    G_CALLBACK (on_quit_diet_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espacediet, espacediet, "espacediet");
  GLADE_HOOKUP_OBJECT (espacediet, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (espacediet, notebookmain_diet, "notebookmain_diet");
  GLADE_HOOKUP_OBJECT (espacediet, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (espacediet, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (espacediet, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (espacediet, bienv_diet, "bienv_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label1, "label1");
  GLADE_HOOKUP_OBJECT (espacediet, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (espacediet, profil_diet_book, "profil_diet_book");
  GLADE_HOOKUP_OBJECT (espacediet, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet1, "pentry_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet3, "pentry_diet3");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet2, "pentry_diet2");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet4, "pentry_diet4");
  GLADE_HOOKUP_OBJECT (espacediet, pspin_diet2, "pspin_diet2");
  GLADE_HOOKUP_OBJECT (espacediet, pspin_diet3, "pspin_diet3");
  GLADE_HOOKUP_OBJECT (espacediet, pspin_diet1, "pspin_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet2, "plabel_diet2");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet3, "plabel_diet3");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet5, "plabel_diet5");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet6, "plabel_diet6");
  GLADE_HOOKUP_OBJECT (espacediet, pcombo_diet1, "pcombo_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, pmodifier_diet1, "pmodifier_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espacediet, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espacediet, image1, "image1");
  GLADE_HOOKUP_OBJECT (espacediet, label28, "label28");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet4, "plabel_diet4");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet1, "plabel_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, imagenom_diet, "imagenom_diet");
  GLADE_HOOKUP_OBJECT (espacediet, imageprenom_diet, "imageprenom_diet");
  GLADE_HOOKUP_OBJECT (espacediet, imagecin_diet, "imagecin_diet");
  GLADE_HOOKUP_OBJECT (espacediet, imagetel_diet, "imagetel_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label6, "label6");
  GLADE_HOOKUP_OBJECT (espacediet, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet, "pentry_diet");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet6, "pentry_diet6");
  GLADE_HOOKUP_OBJECT (espacediet, pentry_diet7, "pentry_diet7");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet9, "plabel_diet9");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet8, "plabel_diet8");
  GLADE_HOOKUP_OBJECT (espacediet, plabel_diet7, "plabel_diet7");
  GLADE_HOOKUP_OBJECT (espacediet, validerp_diet, "validerp_diet");
  GLADE_HOOKUP_OBJECT (espacediet, image2, "image2");
  GLADE_HOOKUP_OBJECT (espacediet, label7, "label7");
  GLADE_HOOKUP_OBJECT (espacediet, toolbar6, "toolbar6");
  GLADE_HOOKUP_OBJECT (espacediet, modifierprofil_diet, "modifierprofil_diet");
  GLADE_HOOKUP_OBJECT (espacediet, changepass_diet, "changepass_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label2, "label2");
  GLADE_HOOKUP_OBJECT (espacediet, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet1, "entryfiche_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet2, "entryfiche_diet2");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet3, "entryfiche_diet3");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet4, "entryfiche_diet4");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet5, "entryfiche_diet5");
  GLADE_HOOKUP_OBJECT (espacediet, toolbar7, "toolbar7");
  GLADE_HOOKUP_OBJECT (espacediet, afficher1_diet, "afficher1_diet");
  GLADE_HOOKUP_OBJECT (espacediet, afficher2_diet, "afficher2_diet");
  GLADE_HOOKUP_OBJECT (espacediet, toolbar8, "toolbar8");
  GLADE_HOOKUP_OBJECT (espacediet, ajouterfiche_diet, "ajouterfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, suprimerfiche_diet, "suprimerfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, modifierfiche_diet, "modifierfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet6, "entryfiche_diet6");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet8, "entryfiche_diet8");
  GLADE_HOOKUP_OBJECT (espacediet, entryfiche_diet7, "entryfiche_diet7");
  GLADE_HOOKUP_OBJECT (espacediet, prenomfiche_diet, "prenomfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, nomfiche_diet, "nomfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, cinfiche_diet, "cinfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, poidfiche_diet, "poidfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, taillefiche_diet, "taillefiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label33, "label33");
  GLADE_HOOKUP_OBJECT (espacediet, tailltourfiche_diet, "tailltourfiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, regimefiche_diet, "regimefiche_diet");
  GLADE_HOOKUP_OBJECT (espacediet, affichagebook_diet, "affichagebook_diet");
  GLADE_HOOKUP_OBJECT (espacediet, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (espacediet, image3, "image3");
  GLADE_HOOKUP_OBJECT (espacediet, image4, "image4");
  GLADE_HOOKUP_OBJECT (espacediet, Guide_diet, "Guide_diet");
  GLADE_HOOKUP_OBJECT (espacediet, guide2_diet, "guide2_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label31, "label31");
  GLADE_HOOKUP_OBJECT (espacediet, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (espacediet, treeview1_diet, "treeview1_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label29, "label29");
  GLADE_HOOKUP_OBJECT (espacediet, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (espacediet, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (espacediet, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (espacediet, treeview2_diet, "treeview2_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label30, "label30");
  GLADE_HOOKUP_OBJECT (espacediet, label3, "label3");
  GLADE_HOOKUP_OBJECT (espacediet, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (espacediet, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (espacediet, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (espacediet, treeview3_diet, "treeview3_diet");
  GLADE_HOOKUP_OBJECT (espacediet, label32, "label32");
  GLADE_HOOKUP_OBJECT (espacediet, entry1_diet, "entry1_diet");
  GLADE_HOOKUP_OBJECT (espacediet, entry2_diet, "entry2_diet");
  GLADE_HOOKUP_OBJECT (espacediet, entry3_diet, "entry3_diet");
  GLADE_HOOKUP_OBJECT (espacediet, entry4_diet, "entry4_diet");
  GLADE_HOOKUP_OBJECT (espacediet, entry5_diet, "entry5_diet");
  GLADE_HOOKUP_OBJECT (espacediet, consulter_diet1, "consulter_diet1");
  GLADE_HOOKUP_OBJECT (espacediet, consulter_diet2, "consulter_diet2");
  GLADE_HOOKUP_OBJECT (espacediet, consulter_diet5, "consulter_diet5");
  GLADE_HOOKUP_OBJECT (espacediet, consulter_diet3, "consulter_diet3");
  GLADE_HOOKUP_OBJECT (espacediet, consulter_diet4, "consulter_diet4");
  GLADE_HOOKUP_OBJECT (espacediet, label4, "label4");
  GLADE_HOOKUP_OBJECT (espacediet, label5, "label5");
  GLADE_HOOKUP_OBJECT (espacediet, toolbar5, "toolbar5");
  GLADE_HOOKUP_OBJECT (espacediet, acc_diet, "acc_diet");
  GLADE_HOOKUP_OBJECT (espacediet, profil_diet5, "profil_diet5");
  GLADE_HOOKUP_OBJECT (espacediet, dichediet, "dichediet");
  GLADE_HOOKUP_OBJECT (espacediet, fichemed_diet, "fichemed_diet");
  GLADE_HOOKUP_OBJECT (espacediet, rend_diet, "rend_diet");
  GLADE_HOOKUP_OBJECT (espacediet, dec_diet, "dec_diet");
  GLADE_HOOKUP_OBJECT (espacediet, quit_diet, "quit_diet");

  return espacediet;
}

