/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1s (void);
GtkWidget* create_window2s (void);
GtkWidget* create_window3s (void);
GtkWidget* create_window4s (void);
GtkWidget* create_window5s (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
GtkWidget* create_window8 (void);
GtkWidget* create_window9 (void);
GtkWidget* create_window10 (void);
GtkWidget* create_window11 (void);
GtkWidget* create_window12 (void);
GtkWidget* create_window13 (void);
GtkWidget* create_window14 (void);
GtkWidget* create_window15 (void);
GtkWidget* create_window16 (void);
GtkWidget* create_window17 (void);
