/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espacemed (void)
{
  GtkWidget *espacemed;
  GtkWidget *fixed3_med;
  GtkWidget *toolbar5_med;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *acc_med;
  GtkWidget *profil_med5;
  GtkWidget *fichemed_med;
  GtkWidget *rend_med;
  GtkWidget *dec_med;
  GtkWidget *quit_med;
  GtkWidget *notebookmain_med;
  GtkWidget *vbox1_med;
  GtkWidget *vbox2_med;
  GtkWidget *fixed10_med;
  GtkWidget *label_accueil_nom;
  GtkWidget *label_accueil_prenom;
  GtkWidget *label_accueil_cin;
  GtkWidget *label_accueil_tel;
  GtkWidget *label_accueil_sex;
  GtkWidget *bienv_med;
  GtkWidget *label3_accueil_cin;
  GtkWidget *label1_accueil_nom;
  GtkWidget *label2_accueil_prenom;
  GtkWidget *label4_accueil_tel;
  GtkWidget *label5_accueil_sex;
  GtkWidget *label1_med;
  GtkWidget *fixed11_med;
  GtkWidget *toolbar6_med;
  GtkWidget *modifierprofil_med;
  GtkWidget *changepass_med;
  GtkWidget *profil_med_book;
  GtkWidget *fixed13_med;
  GtkWidget *pentry_med1;
  GtkWidget *pentry_med3;
  GtkWidget *pentry_med2;
  GtkWidget *pentry_med4;
  GtkObject *pspin_med2_adj;
  GtkWidget *pspin_med2;
  GtkObject *pspin_med3_adj;
  GtkWidget *pspin_med3;
  GtkObject *pspin_med1_adj;
  GtkWidget *pspin_med1;
  GtkWidget *imagenom_med;
  GtkWidget *imageprenom_med;
  GtkWidget *imagecin_med;
  GtkWidget *plabel_med6;
  GtkWidget *plabel_med5;
  GtkWidget *plabel_med2;
  GtkWidget *plabel_med1;
  GtkWidget *plabel_med3;
  GtkWidget *imagetel_med;
  GtkWidget *pemail_med4;
  GtkWidget *pcombo_med1;
  GtkWidget *pmodifier_med1;
  GtkWidget *alignment1_med;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label28;
  GtkWidget *label6_med;
  GtkWidget *fixed14_med;
  GtkWidget *pentry_med;
  GtkWidget *pentry_med6;
  GtkWidget *pentry_med7;
  GtkWidget *plabel_med7;
  GtkWidget *image2_med;
  GtkWidget *plabel_med8;
  GtkWidget *plabel_med9;
  GtkWidget *validerp_med;
  GtkWidget *label7_med;
  GtkWidget *label2_med;
  GtkWidget *fixed16_med;
  GtkWidget *entryfiche_med1;
  GtkWidget *entryfiche_med2;
  GtkWidget *entryfiche_med3;
  GtkWidget *entryfiche_med4;
  GtkWidget *entryfiche_med5;
  GtkWidget *nomfiche_med;
  GtkWidget *toolbar8_med;
  GtkWidget *ajouterfiche_med;
  GtkWidget *suprimerfiche_med;
  GtkWidget *modifierfiche_med;
  GtkWidget *entryfiche_med7;
  GtkWidget *prenomfiche_med;
  GtkWidget *entryfiche_med6;
  GtkWidget *taillefiche_med;
  GtkWidget *poulsfiche_med;
  GtkWidget *agefiche_med;
  GtkWidget *pression_sys_fiche_med;
  GtkWidget *pression_dia_fiche_med;
  GtkWidget *toolbar7_med;
  GtkWidget *afficher1_med;
  GtkWidget *afficher2_med;
  GtkWidget *affichagebook_med;
  GtkWidget *scrolledwindow2_med;
  GtkWidget *viewport1_med;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview20_med;
  GtkWidget *label30_med;
  GtkWidget *label3_med;
  GtkWidget *fixed15_med;
  GtkWidget *treeview2_rendez_med;
  GtkWidget *label30_rendez_med;
  GtkWidget *label31_rendez_med;
  GtkWidget *entry2_jour_rendez_med;
  GtkWidget *entry3_jour_rendez_med;
  GtkWidget *entry4_heure_rendez_med;
  GtkWidget *entry5_salle_rendez_med;
  GtkWidget *label35;
  GtkWidget *label32_rendez_med;
  GtkWidget *combo_salle_rendez_med;
  GtkWidget *label29_rendez_med;
  GtkWidget *button_ajou_rendez_med;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label33;
  GtkWidget *combo_heure_rendez_med;
  GtkWidget *button_supp_rendez_med;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label34;
  GtkWidget *button_mod_rendez_med;
  GtkWidget *alignment5;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label50;
  GtkWidget *label4_med;

  espacemed = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espacemed), _("Espace medecin"));

  fixed3_med = gtk_fixed_new ();
  gtk_widget_show (fixed3_med);
  gtk_container_add (GTK_CONTAINER (espacemed), fixed3_med);

  toolbar5_med = gtk_toolbar_new ();
  gtk_widget_show (toolbar5_med);
  gtk_fixed_put (GTK_FIXED (fixed3_med), toolbar5_med, 0, 0);
  gtk_widget_set_size_request (toolbar5_med, 752, 80);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar5_med), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar5_med));

  tmp_image = gtk_image_new_from_stock ("gtk-home", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  acc_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Accueil"));
  gtk_widget_show (acc_med);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (acc_med), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (acc_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), acc_med);

  tmp_image = gtk_image_new_from_stock ("gtk-orientation-portrait", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  profil_med5 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Profil"));
  gtk_widget_show (profil_med5);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (profil_med5), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), profil_med5);

  tmp_image = gtk_image_new_from_stock ("gtk-index", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  fichemed_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Fiches m\303\251dicaux"));
  gtk_widget_show (fichemed_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (fichemed_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), fichemed_med);

  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  rend_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Les Rendez-vous"));
  gtk_widget_show (rend_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (rend_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), rend_med);

  tmp_image = gtk_image_new_from_stock ("gtk-goto-first", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  dec_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("D\303\251connexion"));
  gtk_widget_show (dec_med);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), dec_med);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  quit_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Quitter"));
  gtk_widget_show (quit_med);
  gtk_container_add (GTK_CONTAINER (toolbar5_med), quit_med);

  notebookmain_med = gtk_notebook_new ();
  gtk_widget_show (notebookmain_med);
  gtk_fixed_put (GTK_FIXED (fixed3_med), notebookmain_med, 0, 72);
  gtk_widget_set_size_request (notebookmain_med, 744, 464);
  GTK_WIDGET_UNSET_FLAGS (notebookmain_med, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (notebookmain_med), FALSE);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebookmain_med), FALSE);

  vbox1_med = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1_med);
  gtk_container_add (GTK_CONTAINER (notebookmain_med), vbox1_med);

  vbox2_med = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2_med);
  gtk_box_pack_start (GTK_BOX (vbox1_med), vbox2_med, TRUE, TRUE, 0);

  fixed10_med = gtk_fixed_new ();
  gtk_widget_show (fixed10_med);
  gtk_box_pack_start (GTK_BOX (vbox2_med), fixed10_med, TRUE, TRUE, 0);

  label_accueil_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label_accueil_nom);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label_accueil_nom, 104, 144);
  gtk_widget_set_size_request (label_accueil_nom, 49, 17);

  label_accueil_prenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label_accueil_prenom);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label_accueil_prenom, 416, 144);
  gtk_widget_set_size_request (label_accueil_prenom, 88, 16);

  label_accueil_cin = gtk_label_new (_("CIN :"));
  gtk_widget_show (label_accueil_cin);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label_accueil_cin, 104, 224);
  gtk_widget_set_size_request (label_accueil_cin, 49, 17);

  label_accueil_tel = gtk_label_new (_("Tel :"));
  gtk_widget_show (label_accueil_tel);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label_accueil_tel, 448, 224);
  gtk_widget_set_size_request (label_accueil_tel, 49, 17);

  label_accueil_sex = gtk_label_new (_("Sex :"));
  gtk_widget_show (label_accueil_sex);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label_accueil_sex, 208, 328);
  gtk_widget_set_size_request (label_accueil_sex, 49, 17);

  bienv_med = gtk_label_new (_("<span  size=\"24000\" style=\"italic\">Bienvenue \303\240 l'espace M\303\251dicale !</span>"));
  gtk_widget_show (bienv_med);
  gtk_fixed_put (GTK_FIXED (fixed10_med), bienv_med, 112, 48);
  gtk_widget_set_size_request (bienv_med, 489, 32);
  gtk_label_set_use_markup (GTK_LABEL (bienv_med), TRUE);

  label3_accueil_cin = gtk_label_new ("");
  gtk_widget_show (label3_accueil_cin);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label3_accueil_cin, 160, 216);
  gtk_widget_set_size_request (label3_accueil_cin, 112, 32);

  label1_accueil_nom = gtk_label_new ("");
  gtk_widget_show (label1_accueil_nom);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label1_accueil_nom, 160, 136);
  gtk_widget_set_size_request (label1_accueil_nom, 136, 32);

  label2_accueil_prenom = gtk_label_new ("");
  gtk_widget_show (label2_accueil_prenom);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label2_accueil_prenom, 504, 136);
  gtk_widget_set_size_request (label2_accueil_prenom, 128, 32);

  label4_accueil_tel = gtk_label_new ("");
  gtk_widget_show (label4_accueil_tel);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label4_accueil_tel, 504, 216);
  gtk_widget_set_size_request (label4_accueil_tel, 120, 32);

  label5_accueil_sex = gtk_label_new ("");
  gtk_widget_show (label5_accueil_sex);
  gtk_fixed_put (GTK_FIXED (fixed10_med), label5_accueil_sex, 264, 320);
  gtk_widget_set_size_request (label5_accueil_sex, 160, 32);

  label1_med = gtk_label_new (_("label1"));
  gtk_widget_show (label1_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_med), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_med), 0), label1_med);

  fixed11_med = gtk_fixed_new ();
  gtk_widget_show (fixed11_med);
  gtk_container_add (GTK_CONTAINER (notebookmain_med), fixed11_med);

  toolbar6_med = gtk_toolbar_new ();
  gtk_widget_show (toolbar6_med);
  gtk_fixed_put (GTK_FIXED (fixed11_med), toolbar6_med, 674, 76);
  gtk_widget_set_size_request (toolbar6_med, 66, 160);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar6_med), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_orientation (GTK_TOOLBAR (toolbar6_med), GTK_ORIENTATION_VERTICAL);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar6_med));

  tmp_image = gtk_image_new_from_stock ("gtk-orientation-landscape", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  modifierprofil_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Modifier \n   profil"));
  gtk_widget_show (modifierprofil_med);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (modifierprofil_med), TRUE);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (modifierprofil_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar6_med), modifierprofil_med);

  tmp_image = gtk_image_new_from_stock ("gtk-paste", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  changepass_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Mot de \n  passe"));
  gtk_widget_show (changepass_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (changepass_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar6_med), changepass_med);

  profil_med_book = gtk_notebook_new ();
  gtk_widget_show (profil_med_book);
  gtk_fixed_put (GTK_FIXED (fixed11_med), profil_med_book, 0, 0);
  gtk_widget_set_size_request (profil_med_book, 672, 349);
  GTK_WIDGET_UNSET_FLAGS (profil_med_book, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (profil_med_book), FALSE);

  fixed13_med = gtk_fixed_new ();
  gtk_widget_show (fixed13_med);
  gtk_container_add (GTK_CONTAINER (profil_med_book), fixed13_med);

  pentry_med1 = gtk_entry_new ();
  gtk_widget_show (pentry_med1);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pentry_med1, 88, 40);
  gtk_widget_set_size_request (pentry_med1, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med1), 8226);

  pentry_med3 = gtk_entry_new ();
  gtk_widget_show (pentry_med3);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pentry_med3, 88, 112);
  gtk_widget_set_size_request (pentry_med3, 160, 24);
  gtk_editable_set_editable (GTK_EDITABLE (pentry_med3), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med3), 8226);

  pentry_med2 = gtk_entry_new ();
  gtk_widget_show (pentry_med2);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pentry_med2, 328, 40);
  gtk_widget_set_size_request (pentry_med2, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med2), 8226);

  pentry_med4 = gtk_entry_new ();
  gtk_widget_show (pentry_med4);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pentry_med4, 328, 112);
  gtk_widget_set_size_request (pentry_med4, 136, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med4), 8226);

  pspin_med2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  pspin_med2 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_med2_adj), 1, 0);
  gtk_widget_show (pspin_med2);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pspin_med2, 248, 168);
  gtk_widget_set_size_request (pspin_med2, 80, 24);

  pspin_med3_adj = gtk_adjustment_new (1980, 1950, 2020, 1, 10, 10);
  pspin_med3 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_med3_adj), 1, 0);
  gtk_widget_show (pspin_med3);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pspin_med3, 344, 168);
  gtk_widget_set_size_request (pspin_med3, 104, 24);

  pspin_med1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  pspin_med1 = gtk_spin_button_new (GTK_ADJUSTMENT (pspin_med1_adj), 1, 0);
  gtk_widget_show (pspin_med1);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pspin_med1, 152, 168);
  gtk_widget_set_size_request (pspin_med1, 84, 24);

  imagenom_med = create_pixmap (espacemed, NULL);
  gtk_widget_show (imagenom_med);
  gtk_fixed_put (GTK_FIXED (fixed13_med), imagenom_med, 248, 40);
  gtk_widget_set_size_request (imagenom_med, 21, 21);

  imageprenom_med = create_pixmap (espacemed, NULL);
  gtk_widget_show (imageprenom_med);
  gtk_fixed_put (GTK_FIXED (fixed13_med), imageprenom_med, 464, 40);
  gtk_widget_set_size_request (imageprenom_med, 21, 21);

  imagecin_med = create_pixmap (espacemed, NULL);
  gtk_widget_show (imagecin_med);
  gtk_fixed_put (GTK_FIXED (fixed13_med), imagecin_med, 248, 112);
  gtk_widget_set_size_request (imagecin_med, 21, 21);

  plabel_med6 = gtk_label_new (_("Sexe"));
  gtk_widget_show (plabel_med6);
  gtk_fixed_put (GTK_FIXED (fixed13_med), plabel_med6, 192, 240);
  gtk_widget_set_size_request (plabel_med6, 44, 16);

  plabel_med5 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (plabel_med5);
  gtk_fixed_put (GTK_FIXED (fixed13_med), plabel_med5, 0, 168);
  gtk_widget_set_size_request (plabel_med5, 144, 24);

  plabel_med2 = gtk_label_new (_("Prenom"));
  gtk_widget_show (plabel_med2);
  gtk_fixed_put (GTK_FIXED (fixed13_med), plabel_med2, 272, 48);
  gtk_widget_set_size_request (plabel_med2, 56, 16);

  plabel_med1 = gtk_label_new (_("Nom"));
  gtk_widget_show (plabel_med1);
  gtk_fixed_put (GTK_FIXED (fixed13_med), plabel_med1, 48, 48);
  gtk_widget_set_size_request (plabel_med1, 37, 16);

  plabel_med3 = gtk_label_new (_("CIN"));
  gtk_widget_show (plabel_med3);
  gtk_fixed_put (GTK_FIXED (fixed13_med), plabel_med3, 48, 120);
  gtk_widget_set_size_request (plabel_med3, 44, 16);

  imagetel_med = create_pixmap (espacemed, NULL);
  gtk_widget_show (imagetel_med);
  gtk_fixed_put (GTK_FIXED (fixed13_med), imagetel_med, 464, 112);
  gtk_widget_set_size_request (imagetel_med, 21, 21);

  pemail_med4 = gtk_label_new (_("tel "));
  gtk_widget_show (pemail_med4);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pemail_med4, 288, 120);
  gtk_widget_set_size_request (pemail_med4, 32, 16);

  pcombo_med1 = gtk_combo_box_new_text ();
  gtk_widget_show (pcombo_med1);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pcombo_med1, 240, 232);
  gtk_widget_set_size_request (pcombo_med1, 120, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pcombo_med1), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pcombo_med1), _("Femme"));

  pmodifier_med1 = gtk_button_new ();
  gtk_widget_show (pmodifier_med1);
  gtk_fixed_put (GTK_FIXED (fixed13_med), pmodifier_med1, 240, 296);
  gtk_widget_set_size_request (pmodifier_med1, 88, 24);

  alignment1_med = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1_med);
  gtk_container_add (GTK_CONTAINER (pmodifier_med1), alignment1_med);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1_med), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox1), label28, FALSE, FALSE, 0);

  label6_med = gtk_label_new (_("label6"));
  gtk_widget_show (label6_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (profil_med_book), gtk_notebook_get_nth_page (GTK_NOTEBOOK (profil_med_book), 0), label6_med);

  fixed14_med = gtk_fixed_new ();
  gtk_widget_show (fixed14_med);
  gtk_container_add (GTK_CONTAINER (profil_med_book), fixed14_med);

  pentry_med = gtk_entry_new ();
  gtk_widget_show (pentry_med);
  gtk_fixed_put (GTK_FIXED (fixed14_med), pentry_med, 240, 64);
  gtk_widget_set_size_request (pentry_med, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med), 8226);

  pentry_med6 = gtk_entry_new ();
  gtk_widget_show (pentry_med6);
  gtk_fixed_put (GTK_FIXED (fixed14_med), pentry_med6, 240, 120);
  gtk_widget_set_size_request (pentry_med6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med6), 8226);

  pentry_med7 = gtk_entry_new ();
  gtk_widget_show (pentry_med7);
  gtk_fixed_put (GTK_FIXED (fixed14_med), pentry_med7, 240, 176);
  gtk_widget_set_size_request (pentry_med7, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (pentry_med7), 8226);

  plabel_med7 = gtk_label_new (_("Ancien mot de passe"));
  gtk_widget_show (plabel_med7);
  gtk_fixed_put (GTK_FIXED (fixed14_med), plabel_med7, 112, 72);
  gtk_widget_set_size_request (plabel_med7, 124, 16);

  image2_med = create_pixmap (espacemed, NULL);
  gtk_widget_show (image2_med);
  gtk_fixed_put (GTK_FIXED (fixed14_med), image2_med, 400, 64);
  gtk_widget_set_size_request (image2_med, 21, 21);

  plabel_med8 = gtk_label_new (_("Nouveau mot de passe"));
  gtk_widget_show (plabel_med8);
  gtk_fixed_put (GTK_FIXED (fixed14_med), plabel_med8, 96, 128);
  gtk_widget_set_size_request (plabel_med8, 140, 16);

  plabel_med9 = gtk_label_new (_("Confirmer mot de passe"));
  gtk_widget_show (plabel_med9);
  gtk_fixed_put (GTK_FIXED (fixed14_med), plabel_med9, 88, 184);
  gtk_widget_set_size_request (plabel_med9, 148, 16);

  validerp_med = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (validerp_med);
  gtk_fixed_put (GTK_FIXED (fixed14_med), validerp_med, 264, 280);
  gtk_widget_set_size_request (validerp_med, 59, 26);

  label7_med = gtk_label_new (_("label7"));
  gtk_widget_show (label7_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (profil_med_book), gtk_notebook_get_nth_page (GTK_NOTEBOOK (profil_med_book), 1), label7_med);

  label2_med = gtk_label_new (_("label2"));
  gtk_widget_show (label2_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_med), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_med), 1), label2_med);

  fixed16_med = gtk_fixed_new ();
  gtk_widget_show (fixed16_med);
  gtk_container_add (GTK_CONTAINER (notebookmain_med), fixed16_med);

  entryfiche_med1 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med1);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med1, 376, 96);
  gtk_widget_set_size_request (entryfiche_med1, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med1), 8226);

  entryfiche_med2 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med2);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med2, 568, 96);
  gtk_widget_set_size_request (entryfiche_med2, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med2), 8226);

  entryfiche_med3 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med3);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med3, 376, 160);
  gtk_widget_set_size_request (entryfiche_med3, 352, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med3), 8226);

  entryfiche_med4 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med4);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med4, 376, 224);
  gtk_widget_set_size_request (entryfiche_med4, 352, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med4), 8226);

  entryfiche_med5 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med5);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med5, 376, 280);
  gtk_widget_set_size_request (entryfiche_med5, 352, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med5), 8226);

  nomfiche_med = gtk_label_new (_("Nom"));
  gtk_widget_show (nomfiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), nomfiche_med, 368, 80);
  gtk_widget_set_size_request (nomfiche_med, 44, 16);

  toolbar8_med = gtk_toolbar_new ();
  gtk_widget_show (toolbar8_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), toolbar8_med, 366, 13);
  gtk_widget_set_size_request (toolbar8_med, 234, 59);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar8_med), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar8_med));

  tmp_image = gtk_image_new_from_stock ("gtk-new", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  ajouterfiche_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Ajouter"));
  gtk_widget_show (ajouterfiche_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (ajouterfiche_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8_med), ajouterfiche_med);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  suprimerfiche_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Suprimer"));
  gtk_widget_show (suprimerfiche_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (suprimerfiche_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8_med), suprimerfiche_med);

  tmp_image = gtk_image_new_from_stock ("gtk-execute", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  modifierfiche_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Modifier"));
  gtk_widget_show (modifierfiche_med);
  gtk_tool_item_set_homogeneous (GTK_TOOL_ITEM (modifierfiche_med), FALSE);
  gtk_container_add (GTK_CONTAINER (toolbar8_med), modifierfiche_med);

  entryfiche_med7 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med7);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med7, 568, 336);
  gtk_widget_set_size_request (entryfiche_med7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med7), 8226);

  prenomfiche_med = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenomfiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), prenomfiche_med, 568, 80);
  gtk_widget_set_size_request (prenomfiche_med, 56, 16);
  gtk_label_set_line_wrap (GTK_LABEL (prenomfiche_med), TRUE);

  entryfiche_med6 = gtk_entry_new ();
  gtk_widget_show (entryfiche_med6);
  gtk_fixed_put (GTK_FIXED (fixed16_med), entryfiche_med6, 376, 336);
  gtk_widget_set_size_request (entryfiche_med6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryfiche_med6), 8226);

  taillefiche_med = gtk_label_new (_("Taille"));
  gtk_widget_show (taillefiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), taillefiche_med, 376, 208);
  gtk_widget_set_size_request (taillefiche_med, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (taillefiche_med), TRUE);

  poulsfiche_med = gtk_label_new (_("Pouls "));
  gtk_widget_show (poulsfiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), poulsfiche_med, 376, 264);
  gtk_widget_set_size_request (poulsfiche_med, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (poulsfiche_med), TRUE);

  agefiche_med = gtk_label_new (_("Age"));
  gtk_widget_show (agefiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), agefiche_med, 376, 144);
  gtk_widget_set_size_request (agefiche_med, 44, 16);
  gtk_label_set_line_wrap (GTK_LABEL (agefiche_med), TRUE);

  pression_sys_fiche_med = gtk_label_new (_("Pression sys(mmhg)"));
  gtk_widget_show (pression_sys_fiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), pression_sys_fiche_med, 376, 320);
  gtk_widget_set_size_request (pression_sys_fiche_med, 160, 16);

  pression_dia_fiche_med = gtk_label_new (_("Pression dia (mmhg)"));
  gtk_widget_show (pression_dia_fiche_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), pression_dia_fiche_med, 568, 320);
  gtk_widget_set_size_request (pression_dia_fiche_med, 160, 16);

  toolbar7_med = gtk_toolbar_new ();
  gtk_widget_show (toolbar7_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), toolbar7_med, 96, 8);
  gtk_widget_set_size_request (toolbar7_med, 192, 64);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar7_med), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar7_med));

  tmp_image = gtk_image_new_from_stock ("gtk-fullscreen", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  afficher1_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _("  Afficher\nAdh\303\251rents"));
  gtk_widget_show (afficher1_med);
  gtk_container_add (GTK_CONTAINER (toolbar7_med), afficher1_med);

  tmp_image = gtk_image_new_from_stock ("gtk-leave-fullscreen", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  afficher2_med = (GtkWidget*) gtk_tool_button_new (tmp_image, _(" Afficher\nles fiches"));
  gtk_widget_show (afficher2_med);
  gtk_container_add (GTK_CONTAINER (toolbar7_med), afficher2_med);

  affichagebook_med = gtk_notebook_new ();
  gtk_widget_show (affichagebook_med);
  gtk_fixed_put (GTK_FIXED (fixed16_med), affichagebook_med, 16, 80);
  gtk_widget_set_size_request (affichagebook_med, 336, 288);
  GTK_WIDGET_UNSET_FLAGS (affichagebook_med, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (affichagebook_med), FALSE);

  scrolledwindow2_med = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2_med);
  gtk_container_add (GTK_CONTAINER (affichagebook_med), scrolledwindow2_med);

  viewport1_med = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1_med);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2_med), viewport1_med);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1_med), GTK_SHADOW_ETCHED_OUT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (viewport1_med), scrolledwindow3);

  treeview20_med = gtk_tree_view_new ();
  gtk_widget_show (treeview20_med);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview20_med);

  label30_med = gtk_label_new (_("label30"));
  gtk_widget_show (label30_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (affichagebook_med), gtk_notebook_get_nth_page (GTK_NOTEBOOK (affichagebook_med), 0), label30_med);

  label3_med = gtk_label_new (_("label3"));
  gtk_widget_show (label3_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_med), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_med), 2), label3_med);

  fixed15_med = gtk_fixed_new ();
  gtk_widget_show (fixed15_med);
  gtk_container_add (GTK_CONTAINER (notebookmain_med), fixed15_med);

  treeview2_rendez_med = gtk_tree_view_new ();
  gtk_widget_show (treeview2_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), treeview2_rendez_med, 48, 80);
  gtk_widget_set_size_request (treeview2_rendez_med, 300, 182);

  label30_rendez_med = gtk_label_new (_("jour :"));
  gtk_widget_show (label30_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), label30_rendez_med, 440, 64);
  gtk_widget_set_size_request (label30_rendez_med, 49, 17);

  label31_rendez_med = gtk_label_new (_("Heure :"));
  gtk_widget_show (label31_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), label31_rendez_med, 432, 128);
  gtk_widget_set_size_request (label31_rendez_med, 49, 17);

  entry2_jour_rendez_med = gtk_entry_new ();
  gtk_widget_show (entry2_jour_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), entry2_jour_rendez_med, 416, 88);
  gtk_widget_set_size_request (entry2_jour_rendez_med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_jour_rendez_med), 8226);

  entry3_jour_rendez_med = gtk_entry_new ();
  gtk_widget_show (entry3_jour_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), entry3_jour_rendez_med, 40, 344);
  gtk_widget_set_size_request (entry3_jour_rendez_med, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_jour_rendez_med), 8226);

  entry4_heure_rendez_med = gtk_entry_new ();
  gtk_widget_show (entry4_heure_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), entry4_heure_rendez_med, 176, 344);
  gtk_widget_set_size_request (entry4_heure_rendez_med, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_heure_rendez_med), 8226);

  entry5_salle_rendez_med = gtk_entry_new ();
  gtk_widget_show (entry5_salle_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), entry5_salle_rendez_med, 312, 344);
  gtk_widget_set_size_request (entry5_salle_rendez_med, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_salle_rendez_med), 8226);

  label35 = gtk_label_new (_("Les rendez-vous a supprimer :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed15_med), label35, 40, 328);
  gtk_widget_set_size_request (label35, 232, 16);

  label32_rendez_med = gtk_label_new (_("Salle :"));
  gtk_widget_show (label32_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), label32_rendez_med, 432, 192);
  gtk_widget_set_size_request (label32_rendez_med, 49, 17);

  combo_salle_rendez_med = gtk_combo_box_new_text ();
  gtk_widget_show (combo_salle_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), combo_salle_rendez_med, 416, 216);
  gtk_widget_set_size_request (combo_salle_rendez_med, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_salle_rendez_med), _("salle_A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_salle_rendez_med), _("salle_B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_salle_rendez_med), _("salle_C"));

  label29_rendez_med = gtk_label_new (_("Ajout de disponibilit\303\251 :"));
  gtk_widget_show (label29_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), label29_rendez_med, 64, 24);
  gtk_widget_set_size_request (label29_rendez_med, 169, 16);

  button_ajou_rendez_med = gtk_button_new ();
  gtk_widget_show (button_ajou_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), button_ajou_rendez_med, 408, 16);
  gtk_widget_set_size_request (button_ajou_rendez_med, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajou_rendez_med), alignment1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox2), label33, FALSE, FALSE, 0);

  combo_heure_rendez_med = gtk_combo_box_new_text ();
  gtk_widget_show (combo_heure_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), combo_heure_rendez_med, 416, 152);
  gtk_widget_set_size_request (combo_heure_rendez_med, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_heure_rendez_med), _("8==>12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_heure_rendez_med), _("14==>17"));

  button_supp_rendez_med = gtk_button_new ();
  gtk_widget_show (button_supp_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), button_supp_rendez_med, 488, 336);
  gtk_widget_set_size_request (button_supp_rendez_med, 112, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_supp_rendez_med), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox3), label34, FALSE, FALSE, 0);

  button_mod_rendez_med = gtk_button_new ();
  gtk_widget_show (button_mod_rendez_med);
  gtk_fixed_put (GTK_FIXED (fixed15_med), button_mod_rendez_med, 616, 336);
  gtk_widget_set_size_request (button_mod_rendez_med, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_mod_rendez_med), alignment5);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox6), label50, FALSE, FALSE, 0);

  label4_med = gtk_label_new (_("label4"));
  gtk_widget_show (label4_med);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookmain_med), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookmain_med), 3), label4_med);

  g_signal_connect ((gpointer) espacemed, "show",
                    G_CALLBACK (on_espacemed_show),
                    NULL);
  g_signal_connect ((gpointer) acc_med, "clicked",
                    G_CALLBACK (on_accuei_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) profil_med5, "clicked",
                    G_CALLBACK (on_profil_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) fichemed_med, "clicked",
                    G_CALLBACK (on_fichemed_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) rend_med, "clicked",
                    G_CALLBACK (on_rendez_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) dec_med, "clicked",
                    G_CALLBACK (on_dec_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit_med, "clicked",
                    G_CALLBACK (on_quit_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) notebookmain_med, "show",
                    G_CALLBACK (on_notebookmain_med_show),
                    NULL);
  g_signal_connect ((gpointer) modifierprofil_med, "clicked",
                    G_CALLBACK (on_modifierprofil_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) changepass_med, "clicked",
                    G_CALLBACK (on_changepass_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) pmodifier_med1, "clicked",
                    G_CALLBACK (on_pmodifier_med1_clicked),
                    NULL);
  g_signal_connect ((gpointer) validerp_med, "clicked",
                    G_CALLBACK (on_validerp_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterfiche_med, "clicked",
                    G_CALLBACK (on_ajouterfiche_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) suprimerfiche_med, "clicked",
                    G_CALLBACK (on_suprimerfiche_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierfiche_med, "clicked",
                    G_CALLBACK (on_modifierfiche_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher1_med, "clicked",
                    G_CALLBACK (on_afficher1_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher2_med, "clicked",
                    G_CALLBACK (on_afficher2_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview20_med, "row_activated",
                    G_CALLBACK (on_treeview20_med_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview2_rendez_med, "row_activated",
                    G_CALLBACK (on_treeview2_med_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_ajou_rendez_med, "clicked",
                    G_CALLBACK (on_button_ajou_rendez_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supp_rendez_med, "clicked",
                    G_CALLBACK (on_button_supp_rendez_med_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod_rendez_med, "clicked",
                    G_CALLBACK (on_button_mod_rendez_med_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espacemed, espacemed, "espacemed");
  GLADE_HOOKUP_OBJECT (espacemed, fixed3_med, "fixed3_med");
  GLADE_HOOKUP_OBJECT (espacemed, toolbar5_med, "toolbar5_med");
  GLADE_HOOKUP_OBJECT (espacemed, acc_med, "acc_med");
  GLADE_HOOKUP_OBJECT (espacemed, profil_med5, "profil_med5");
  GLADE_HOOKUP_OBJECT (espacemed, fichemed_med, "fichemed_med");
  GLADE_HOOKUP_OBJECT (espacemed, rend_med, "rend_med");
  GLADE_HOOKUP_OBJECT (espacemed, dec_med, "dec_med");
  GLADE_HOOKUP_OBJECT (espacemed, quit_med, "quit_med");
  GLADE_HOOKUP_OBJECT (espacemed, notebookmain_med, "notebookmain_med");
  GLADE_HOOKUP_OBJECT (espacemed, vbox1_med, "vbox1_med");
  GLADE_HOOKUP_OBJECT (espacemed, vbox2_med, "vbox2_med");
  GLADE_HOOKUP_OBJECT (espacemed, fixed10_med, "fixed10_med");
  GLADE_HOOKUP_OBJECT (espacemed, label_accueil_nom, "label_accueil_nom");
  GLADE_HOOKUP_OBJECT (espacemed, label_accueil_prenom, "label_accueil_prenom");
  GLADE_HOOKUP_OBJECT (espacemed, label_accueil_cin, "label_accueil_cin");
  GLADE_HOOKUP_OBJECT (espacemed, label_accueil_tel, "label_accueil_tel");
  GLADE_HOOKUP_OBJECT (espacemed, label_accueil_sex, "label_accueil_sex");
  GLADE_HOOKUP_OBJECT (espacemed, bienv_med, "bienv_med");
  GLADE_HOOKUP_OBJECT (espacemed, label3_accueil_cin, "label3_accueil_cin");
  GLADE_HOOKUP_OBJECT (espacemed, label1_accueil_nom, "label1_accueil_nom");
  GLADE_HOOKUP_OBJECT (espacemed, label2_accueil_prenom, "label2_accueil_prenom");
  GLADE_HOOKUP_OBJECT (espacemed, label4_accueil_tel, "label4_accueil_tel");
  GLADE_HOOKUP_OBJECT (espacemed, label5_accueil_sex, "label5_accueil_sex");
  GLADE_HOOKUP_OBJECT (espacemed, label1_med, "label1_med");
  GLADE_HOOKUP_OBJECT (espacemed, fixed11_med, "fixed11_med");
  GLADE_HOOKUP_OBJECT (espacemed, toolbar6_med, "toolbar6_med");
  GLADE_HOOKUP_OBJECT (espacemed, modifierprofil_med, "modifierprofil_med");
  GLADE_HOOKUP_OBJECT (espacemed, changepass_med, "changepass_med");
  GLADE_HOOKUP_OBJECT (espacemed, profil_med_book, "profil_med_book");
  GLADE_HOOKUP_OBJECT (espacemed, fixed13_med, "fixed13_med");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med1, "pentry_med1");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med3, "pentry_med3");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med2, "pentry_med2");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med4, "pentry_med4");
  GLADE_HOOKUP_OBJECT (espacemed, pspin_med2, "pspin_med2");
  GLADE_HOOKUP_OBJECT (espacemed, pspin_med3, "pspin_med3");
  GLADE_HOOKUP_OBJECT (espacemed, pspin_med1, "pspin_med1");
  GLADE_HOOKUP_OBJECT (espacemed, imagenom_med, "imagenom_med");
  GLADE_HOOKUP_OBJECT (espacemed, imageprenom_med, "imageprenom_med");
  GLADE_HOOKUP_OBJECT (espacemed, imagecin_med, "imagecin_med");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med6, "plabel_med6");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med5, "plabel_med5");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med2, "plabel_med2");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med1, "plabel_med1");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med3, "plabel_med3");
  GLADE_HOOKUP_OBJECT (espacemed, imagetel_med, "imagetel_med");
  GLADE_HOOKUP_OBJECT (espacemed, pemail_med4, "pemail_med4");
  GLADE_HOOKUP_OBJECT (espacemed, pcombo_med1, "pcombo_med1");
  GLADE_HOOKUP_OBJECT (espacemed, pmodifier_med1, "pmodifier_med1");
  GLADE_HOOKUP_OBJECT (espacemed, alignment1_med, "alignment1_med");
  GLADE_HOOKUP_OBJECT (espacemed, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espacemed, image1, "image1");
  GLADE_HOOKUP_OBJECT (espacemed, label28, "label28");
  GLADE_HOOKUP_OBJECT (espacemed, label6_med, "label6_med");
  GLADE_HOOKUP_OBJECT (espacemed, fixed14_med, "fixed14_med");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med, "pentry_med");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med6, "pentry_med6");
  GLADE_HOOKUP_OBJECT (espacemed, pentry_med7, "pentry_med7");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med7, "plabel_med7");
  GLADE_HOOKUP_OBJECT (espacemed, image2_med, "image2_med");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med8, "plabel_med8");
  GLADE_HOOKUP_OBJECT (espacemed, plabel_med9, "plabel_med9");
  GLADE_HOOKUP_OBJECT (espacemed, validerp_med, "validerp_med");
  GLADE_HOOKUP_OBJECT (espacemed, label7_med, "label7_med");
  GLADE_HOOKUP_OBJECT (espacemed, label2_med, "label2_med");
  GLADE_HOOKUP_OBJECT (espacemed, fixed16_med, "fixed16_med");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med1, "entryfiche_med1");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med2, "entryfiche_med2");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med3, "entryfiche_med3");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med4, "entryfiche_med4");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med5, "entryfiche_med5");
  GLADE_HOOKUP_OBJECT (espacemed, nomfiche_med, "nomfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, toolbar8_med, "toolbar8_med");
  GLADE_HOOKUP_OBJECT (espacemed, ajouterfiche_med, "ajouterfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, suprimerfiche_med, "suprimerfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, modifierfiche_med, "modifierfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med7, "entryfiche_med7");
  GLADE_HOOKUP_OBJECT (espacemed, prenomfiche_med, "prenomfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, entryfiche_med6, "entryfiche_med6");
  GLADE_HOOKUP_OBJECT (espacemed, taillefiche_med, "taillefiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, poulsfiche_med, "poulsfiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, agefiche_med, "agefiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, pression_sys_fiche_med, "pression_sys_fiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, pression_dia_fiche_med, "pression_dia_fiche_med");
  GLADE_HOOKUP_OBJECT (espacemed, toolbar7_med, "toolbar7_med");
  GLADE_HOOKUP_OBJECT (espacemed, afficher1_med, "afficher1_med");
  GLADE_HOOKUP_OBJECT (espacemed, afficher2_med, "afficher2_med");
  GLADE_HOOKUP_OBJECT (espacemed, affichagebook_med, "affichagebook_med");
  GLADE_HOOKUP_OBJECT (espacemed, scrolledwindow2_med, "scrolledwindow2_med");
  GLADE_HOOKUP_OBJECT (espacemed, viewport1_med, "viewport1_med");
  GLADE_HOOKUP_OBJECT (espacemed, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (espacemed, treeview20_med, "treeview20_med");
  GLADE_HOOKUP_OBJECT (espacemed, label30_med, "label30_med");
  GLADE_HOOKUP_OBJECT (espacemed, label3_med, "label3_med");
  GLADE_HOOKUP_OBJECT (espacemed, fixed15_med, "fixed15_med");
  GLADE_HOOKUP_OBJECT (espacemed, treeview2_rendez_med, "treeview2_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, label30_rendez_med, "label30_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, label31_rendez_med, "label31_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, entry2_jour_rendez_med, "entry2_jour_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, entry3_jour_rendez_med, "entry3_jour_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, entry4_heure_rendez_med, "entry4_heure_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, entry5_salle_rendez_med, "entry5_salle_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, label35, "label35");
  GLADE_HOOKUP_OBJECT (espacemed, label32_rendez_med, "label32_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, combo_salle_rendez_med, "combo_salle_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, label29_rendez_med, "label29_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, button_ajou_rendez_med, "button_ajou_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espacemed, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espacemed, image2, "image2");
  GLADE_HOOKUP_OBJECT (espacemed, label33, "label33");
  GLADE_HOOKUP_OBJECT (espacemed, combo_heure_rendez_med, "combo_heure_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, button_supp_rendez_med, "button_supp_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espacemed, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (espacemed, image3, "image3");
  GLADE_HOOKUP_OBJECT (espacemed, label34, "label34");
  GLADE_HOOKUP_OBJECT (espacemed, button_mod_rendez_med, "button_mod_rendez_med");
  GLADE_HOOKUP_OBJECT (espacemed, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (espacemed, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (espacemed, image6, "image6");
  GLADE_HOOKUP_OBJECT (espacemed, label50, "label50");
  GLADE_HOOKUP_OBJECT (espacemed, label4_med, "label4_med");

  return espacemed;
}

GtkWidget*
create_espace_login (void)
{
  GtkWidget *espace_login;
  GtkWidget *fixed_username;
  GtkWidget *entry1_username;
  GtkWidget *entry2_password;
  GtkWidget *label_login_username;
  GtkWidget *label_login_password_;
  GtkWidget *button_exit;
  GtkWidget *alignment4;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label49;
  GtkWidget *button_login_;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label48;

  espace_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_login), _("espace_med"));

  fixed_username = gtk_fixed_new ();
  gtk_widget_show (fixed_username);
  gtk_container_add (GTK_CONTAINER (espace_login), fixed_username);

  entry1_username = gtk_entry_new ();
  gtk_widget_show (entry1_username);
  gtk_fixed_put (GTK_FIXED (fixed_username), entry1_username, 176, 80);
  gtk_widget_set_size_request (entry1_username, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_username), 8226);

  entry2_password = gtk_entry_new ();
  gtk_widget_show (entry2_password);
  gtk_fixed_put (GTK_FIXED (fixed_username), entry2_password, 176, 136);
  gtk_widget_set_size_request (entry2_password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_password), 8226);

  label_login_username = gtk_label_new (_("Username :"));
  gtk_widget_show (label_login_username);
  gtk_fixed_put (GTK_FIXED (fixed_username), label_login_username, 40, 80);
  gtk_widget_set_size_request (label_login_username, 112, 32);

  label_login_password_ = gtk_label_new (_("Password :"));
  gtk_widget_show (label_login_password_);
  gtk_fixed_put (GTK_FIXED (fixed_username), label_login_password_, 48, 136);
  gtk_widget_set_size_request (label_login_password_, 96, 32);

  button_exit = gtk_button_new ();
  gtk_widget_show (button_exit);
  gtk_fixed_put (GTK_FIXED (fixed_username), button_exit, 208, 224);
  gtk_widget_set_size_request (button_exit, 80, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_exit), alignment4);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("exit"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox5), label49, FALSE, FALSE, 0);

  button_login_ = gtk_button_new ();
  gtk_widget_show (button_login_);
  gtk_fixed_put (GTK_FIXED (fixed_username), button_login_, 88, 224);
  gtk_widget_set_size_request (button_login_, 80, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_login_), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("login "));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox4), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_exit, "clicked",
                    G_CALLBACK (on_button_exit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_login_, "clicked",
                    G_CALLBACK (on_button_login__clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_login, espace_login, "espace_login");
  GLADE_HOOKUP_OBJECT (espace_login, fixed_username, "fixed_username");
  GLADE_HOOKUP_OBJECT (espace_login, entry1_username, "entry1_username");
  GLADE_HOOKUP_OBJECT (espace_login, entry2_password, "entry2_password");
  GLADE_HOOKUP_OBJECT (espace_login, label_login_username, "label_login_username");
  GLADE_HOOKUP_OBJECT (espace_login, label_login_password_, "label_login_password_");
  GLADE_HOOKUP_OBJECT (espace_login, button_exit, "button_exit");
  GLADE_HOOKUP_OBJECT (espace_login, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (espace_login, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (espace_login, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace_login, label49, "label49");
  GLADE_HOOKUP_OBJECT (espace_login, button_login_, "button_login_");
  GLADE_HOOKUP_OBJECT (espace_login, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (espace_login, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (espace_login, image4, "image4");
  GLADE_HOOKUP_OBJECT (espace_login, label48, "label48");

  return espace_login;
}

