/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *label3;
  GtkWidget *label7;
  GtkWidget *checkbutton1;
  GtkWidget *button4;
  GtkWidget *image3;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label6;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 400, 300);
  gtk_window_set_title (GTK_WINDOW (window1), _("Login"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 32, 64);
  gtk_widget_set_size_request (entry1, 336, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 32, 128);
  gtk_widget_set_size_request (entry2, 336, 24);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 112);
  gtk_widget_set_size_request (label2, 88, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label2), TRUE);

  label1 = gtk_label_new (_("Nom d'utilisateur"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 48);
  gtk_widget_set_size_request (label1, 112, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);

  label3 = gtk_label_new (_("Cacher le mot de passe"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 56, 160);
  gtk_widget_set_size_request (label3, 136, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);

  label7 = gtk_label_new ("");
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 48, 16);
  gtk_widget_set_size_request (label7, 312, 16);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 32, 160);
  gtk_widget_set_size_request (checkbutton1, 16, 16);
  gtk_button_set_focus_on_click (GTK_BUTTON (checkbutton1), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 360, 264);
  gtk_widget_set_size_request (button4, 35, 32);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (button4), image3);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 96, 256);
  gtk_widget_set_size_request (button3, 216, 24);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Connecter en tant qu'un visiteur"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 96, 208);
  gtk_widget_set_size_request (button2, 216, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 209, 156);
  gtk_widget_set_size_request (button1, 160, 27);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Mot de passe oubli\303\251 ?"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *fixed9;
  GtkWidget *label13;
  GtkWidget *button5;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *button6;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *label8;
  GtkWidget *fixed3;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label20;
  GtkWidget *label9;
  GtkWidget *fixed4;
  GtkWidget *button8;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *button12;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label21;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label25;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label24;
  GtkWidget *button15;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label32;
  GtkWidget *button16;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label33;
  GtkWidget *button17;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label34;
  GtkWidget *button18;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label35;
  GtkWidget *button19;
  GtkWidget *combobox1;
  GtkWidget *image19;
  GtkWidget *image20;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *image21;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *image22;
  GtkWidget *label41;
  GtkWidget *image23;
  GtkWidget *label36;
  GtkWidget *image24;
  GtkWidget *label10;
  GtkWidget *fixed5;
  GtkWidget *button9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label18;
  GtkWidget *button13;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label22;
  GtkWidget *label11;
  GtkWidget *fixed6;
  GtkWidget *button10;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label19;
  GtkWidget *button14;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label23;
  GtkWidget *label12;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 500, 400);
  gtk_window_set_title (GTK_WINDOW (window2), _("Espace Di\303\251t\303\251ticien"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER_ALWAYS);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window2), notebook1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed2,
                                      TRUE, TRUE, GTK_PACK_START);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed7, 0, 0);
  gtk_widget_set_size_request (fixed7, 0, 0);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed8, 0, 0);
  gtk_widget_set_size_request (fixed8, 0, 0);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed9, 0, 0);
  gtk_widget_set_size_request (fixed9, 0, 0);

  label13 = gtk_label_new (_("Bienvenu \303\240 l'espace Di\303\251t\303\251ticien"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 160, 152);
  gtk_widget_set_size_request (label13, 196, 16);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 376, 296);
  gtk_widget_set_size_request (button5, 115, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 376, 328);
  gtk_widget_set_size_request (button6, 115, 24);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  label8 = gtk_label_new (_("Page d'acceuil"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label8);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed3,
                                      TRUE, TRUE, GTK_PACK_START);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 376, 296);
  gtk_widget_set_size_request (button7, 115, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 376, 328);
  gtk_widget_set_size_request (button11, 115, 24);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox10), label20, FALSE, FALSE, 0);

  label9 = gtk_label_new (_("Fiche \npersonnelle"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed4,
                                      TRUE, TRUE, GTK_PACK_START);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed4), button8, 376, 296);
  gtk_widget_set_size_request (button8, 115, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button8), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 376, 328);
  gtk_widget_set_size_request (button12, 115, 24);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button12), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox11), label21, FALSE, FALSE, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 112, 88);
  gtk_widget_set_size_request (entry3, 96, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 288, 88);
  gtk_widget_set_size_request (entry4, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 112, 192);
  gtk_widget_set_size_request (entry5, 88, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 288, 192);
  gtk_widget_set_size_request (entry6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 176, 136);
  gtk_widget_set_size_request (spinbutton1, 60, 24);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 280, 136);
  gtk_widget_set_size_request (spinbutton2, 60, 24);

  spinbutton3_adj = gtk_adjustment_new (2018, 2018, 2020, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 384, 136);
  gtk_widget_set_size_request (spinbutton3, 60, 24);

  label25 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 232, 93);
  gtk_widget_set_size_request (label25, 60, 16);

  label28 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 344, 144);
  gtk_widget_set_size_request (label28, 44, 16);

  label27 = gtk_label_new (_("mois"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 240, 144);
  gtk_widget_set_size_request (label27, 44, 16);

  label26 = gtk_label_new (_("Jour"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 136, 144);
  gtk_widget_set_size_request (label26, 44, 16);

  label29 = gtk_label_new (_("Date de creation\nou modification"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 16, 136);
  gtk_widget_set_size_request (label29, 144, 32);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_CENTER);

  label30 = gtk_label_new (_("Age"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 72, 200);
  gtk_widget_set_size_request (label30, 44, 16);

  label31 = gtk_label_new (_("Taille"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 240, 200);
  gtk_widget_set_size_request (label31, 52, 16);

  label24 = gtk_label_new (_("Nom"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 72, 96);
  gtk_widget_set_size_request (label24, 44, 16);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed4), button15, 352, 35);
  gtk_widget_set_size_request (button15, 128, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button15), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Charger la fiche"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox14), label32, FALSE, FALSE, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed4), button16, 152, 264);
  gtk_widget_set_size_request (button16, 72, 24);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button16), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox15), label33, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed4), button17, 232, 264);
  gtk_widget_set_size_request (button17, 88, 24);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button17), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Suprimer"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox16), label34, FALSE, FALSE, 0);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed4), button18, 200, 296);
  gtk_widget_set_size_request (button18, 82, 24);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button18), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox17), label35, FALSE, FALSE, 0);

  button19 = gtk_button_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed4), button19, 16, 40);
  gtk_widget_set_size_request (button19, 82, 24);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 112, 32);
  gtk_widget_set_size_request (combobox1, 224, 32);

  image19 = create_pixmap (window2, NULL);
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed4), image19, 208, 89);
  gtk_widget_set_size_request (image19, 21, 21);

  image20 = create_pixmap (window2, NULL);
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed4), image20, 448, 90);
  gtk_widget_set_size_request (image20, 21, 21);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 112, 112);
  gtk_widget_set_size_request (label37, 96, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed4), label38, 288, 112);
  gtk_widget_set_size_request (label38, 160, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label38), TRUE);

  image21 = create_pixmap (window2, NULL);
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed4), image21, 448, 136);
  gtk_widget_set_size_request (image21, 21, 21);

  label39 = gtk_label_new ("");
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed4), label39, 144, 168);
  gtk_widget_set_size_request (label39, 304, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label39), TRUE);

  label40 = gtk_label_new ("");
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed4), label40, 112, 216);
  gtk_widget_set_size_request (label40, 88, 16);

  image22 = create_pixmap (window2, NULL);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed4), image22, 200, 192);
  gtk_widget_set_size_request (image22, 21, 21);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed4), label41, 288, 216);
  gtk_widget_set_size_request (label41, 160, 16);
  gtk_label_set_line_wrap (GTK_LABEL (label41), TRUE);

  image23 = create_pixmap (window2, NULL);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed4), image23, 448, 192);
  gtk_widget_set_size_request (image23, 21, 21);

  label36 = gtk_label_new ("");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 128, 8);
  gtk_widget_set_size_request (label36, 200, 16);

  image24 = create_pixmap (window2, NULL);
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed4), image24, 104, 5);
  gtk_widget_set_size_request (image24, 21, 21);

  label10 = gtk_label_new (_("Gestion des \nfichies di\303\251t\303\251tique"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label10);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed5,
                                      TRUE, TRUE, GTK_PACK_START);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 376, 296);
  gtk_widget_set_size_request (button9, 115, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 376, 328);
  gtk_widget_set_size_request (button13, 115, 24);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button13), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox12), label22, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("Consulter une \nfiche m\303\251dicale"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label11);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), fixed6,
                                      TRUE, TRUE, GTK_PACK_START);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 376, 296);
  gtk_widget_set_size_request (button10, 115, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button10), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("D\303\251connecter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed6), button14, 376, 328);
  gtk_widget_set_size_request (button14, 115, 24);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button14), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox13), label23, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Gestion des\nRendez-vous"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label12);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label12), TRUE);

  g_signal_connect ((gpointer) window2, "show",
                    G_CALLBACK (on_window2_show),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window2, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, image5, "image5");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, button11, "button11");
  GLADE_HOOKUP_OBJECT (window2, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window2, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window2, image11, "image11");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2, image8, "image8");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window2, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window2, image12, "image12");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window2, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window2, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window2, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, label27, "label27");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, label29, "label29");
  GLADE_HOOKUP_OBJECT (window2, label30, "label30");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, button15, "button15");
  GLADE_HOOKUP_OBJECT (window2, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window2, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window2, image15, "image15");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");
  GLADE_HOOKUP_OBJECT (window2, button16, "button16");
  GLADE_HOOKUP_OBJECT (window2, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window2, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window2, image16, "image16");
  GLADE_HOOKUP_OBJECT (window2, label33, "label33");
  GLADE_HOOKUP_OBJECT (window2, button17, "button17");
  GLADE_HOOKUP_OBJECT (window2, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window2, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window2, image17, "image17");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, button18, "button18");
  GLADE_HOOKUP_OBJECT (window2, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window2, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window2, image18, "image18");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, button19, "button19");
  GLADE_HOOKUP_OBJECT (window2, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window2, image19, "image19");
  GLADE_HOOKUP_OBJECT (window2, image20, "image20");
  GLADE_HOOKUP_OBJECT (window2, label37, "label37");
  GLADE_HOOKUP_OBJECT (window2, label38, "label38");
  GLADE_HOOKUP_OBJECT (window2, image21, "image21");
  GLADE_HOOKUP_OBJECT (window2, label39, "label39");
  GLADE_HOOKUP_OBJECT (window2, label40, "label40");
  GLADE_HOOKUP_OBJECT (window2, image22, "image22");
  GLADE_HOOKUP_OBJECT (window2, label41, "label41");
  GLADE_HOOKUP_OBJECT (window2, image23, "image23");
  GLADE_HOOKUP_OBJECT (window2, label36, "label36");
  GLADE_HOOKUP_OBJECT (window2, image24, "image24");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window2, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window2, image9, "image9");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, button13, "button13");
  GLADE_HOOKUP_OBJECT (window2, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window2, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window2, image13, "image13");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window2, button10, "button10");
  GLADE_HOOKUP_OBJECT (window2, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window2, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, button14, "button14");
  GLADE_HOOKUP_OBJECT (window2, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window2, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window2, image14, "image14");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");

  return window2;
}

